### ISSUE TITLE
add Full 

### ISSUE THREAD

**Issue by jajasuparja** [Ejdamm/Chart.js-PHP#1]
Hi, 

I tried what you suggest to me for option in chart js, like bellow:
$options = array(
    'scales' => array(
        'yAxes' => array(
            array(
                'scaleLabel' => array(
                    'display' => true,
                    'labelString' => 'Time in Seconds',
                    'fontColor' => 'red'
                )
            )
        )
    )
);

and it woks. Thanks. buat i tried to add new option as follow to add legend but it does not work.

$options = array(
    'scales' => array(
        'yAxes' => array(
            array(
                'scaleLabel' => array(
                    'display' => true,
                    'labelString' => '',
                    'fontColor' => 'red',
                    'responsive' => false
                )
            )
          )
    )
    
    'legend'=> array (
       'horizontalAlign'=>'left', // "center" , "right"
       'verticalAlign'=>'center',  // "top" , "bottom"
        'fontSize' =>'15'
     )
    
);

need your advice.

**Comment by adamgeorgsson** [comment]
Hi,

You can read about legend [here](http://www.chartjs.org/docs/latest/configuration/legend.html)
Font options should be inside a labels array and there are no horizontalAlign or verticalAlign. Instead there is position but the only options are top, bottom, left and right. So you can align it to left but not center it vertically.
Also, your 'responsive' => false is in the wrong place.

```
$options = array(
    'responsive' => false,
    'scales' => array(
        'yAxes' => array(
            array(
                'scaleLabel' => array(
                    'display' => true,
                    'labelString' => '',
                    'fontColor' => 'red',
                )
            )
        )
    ),
    'legend' => array (
        'position' => 'left',
        'labels' => array (
            'fontSize' => 15
        )
    )
);
```
Note that fontSize value is a number and not a string (e.g. 15 and not '15').
