### ISSUE TITLE
Auto-generated data & options question/issue

### ISSUE THREAD

**Issue by jackttcoms** [Ejdamm/Chart.js-PHP#10]
This class is really helpful but I am doing view stats and some days there will be 0 views so how do i make it so that it does not just skip the date and says 0.

Here is an example in months of what i mean:
 jan, feb, apr, jun, jul, aug, sep, nov, dec
it missed march,may & october so basically how to I make it so that it does not miss a few months and shows them as 0 instead of not showing them at all. Thanks

Also i have set it to always begin at 0 but for some reason it is not. Why could this be? Thanks
```
        $viewsGraph = [
            'labels' => ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
            'datasets' => [[
                'data' =>[8, 7, 8, 9, 6],
                'backgroundColor' => '#007bff',
                'borderColor' => '#005cbf',
                'label' => 'Weekly Views'
            ]]
        ];
        $options = [
            'responsive' => true,
            'scales' => [[
                'yAxes' => [
                    'ticks' => [
                        'beginAtZero' => true
                    ]
                ]
            ]]
        ];
        $attributes = ['id' => 'example', 'width' => 500, 'height' => 200];
        $Line = new ChartJS('bar', $viewsGraph, $options, $attributes);
```

This is the html side:
```

    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.bundle.min.js"></script>
    <script src="http://localhost/new/js/driver.js"></script>
    <script>
    (function() {
      loadChartJsPhp();
    })();
    </script>
```

**Comment by adamgeorgsson** [comment]
Hi
beginAtZero not working: You have the double brackets on the wrong level. Try
```
        $options = [
            'responsive' => true,
            'scales' => [
                'yAxes' => [[
                    'ticks' => [
                        'beginAtZero' => true
                    ]
                ]]
            ]
        ];
```

Regarding the first problem: I don't think I understand the issue. Having
`'labels' => ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],`
and
`'data' =>[8, 7, 0, 9, 6],`
gives a gap in the chart. Wednesday is still there but with zero value.

**Comment by jackttcoms** [comment]
Hi there,
Thanks the beginAtZero works great now, also sorry I probably did not word it correctly.

What i'm trying to say is I have a views table shown below, it tracks all the views and when people view certain items it inserts a new row. With this class, I need to show data weekly but as you can see when there are missing days such as 22nd, 23rd, 24th & 26th, I need it to display a 0 instead of no data at all.

Right now my sql query, this only gets data in the db, i need to make it so that if data is missing it can fill in the missing date and set to 0 or however the best way to achieve this is.
```
select DATE( date ), COUNT(*)
                from chewi_views
                group by DATE( date )
```

Here is the view table:
![image](https://user-images.githubusercontent.com/26184209/47566486-d2e36200-d923-11e8-8cc9-5bca941eca6f.png)

I need something like this that shows a 7 day period of data. https://codepen.io/adrianhurt/pen/GqvBzo

In your example you do static data, could you do a php example where you make a feake database etc?

Thanks sorry if i have worded it too much. This is the best chart class I have found and really want it to work :) Thanks again for your help.

**Comment by adamgeorgsson** [comment]
I actually did something similar recently but it is not something chart.js or this wrapper can solve magically. My solution was to create an array with all dates in a given week, let's call it $allDates and the sql result for $sqlDates. Then I looped through $allDates. If there was a match in $sqlDates: add it to the dataset. Otherwise add a 0.

**Comment by jackttcoms** [comment]
Ok so like this?

```
<?php
function GetCurrentWeekDates()
{
    if (date('D') != 'Mon') {
        $startdate = date('Y-m-d', strtotime('last Monday'));
    } else {
        $startdate = date('Y-m-d');
    }

//always next saturday
    if (date('D') != 'Sat') {
        $enddate = date('Y-m-d', strtotime('next Saturday'));
    } else {
        $enddate = date('Y-m-d');
    }

    $DateArray = array();
    $timestamp = strtotime($startdate);
    while ($startdate <= $enddate) {
        $startdate = date('Y-m-d', $timestamp);
        $DateArray[] = $startdate;
        $timestamp = strtotime('+1 days', strtotime($startdate));
    }
    return $DateArray;
}
print_r(GetCurrentWeekDates());
```

> Then I looped through $allDates. If there was a match in $sqlDates: add it to the dataset. Otherwise add a 0

Do you mean a foreach? Thanks very much.

**Comment by adamgeorgsson** [comment]
Yeah a foreach on the $allDates.
Something like
```
$allDates = GetCurrentWeekDates();
$dataset = [];
foreach ($allDates as $date) {
    if (in_array($date, $sqlDates)) {
        $dataset[] = $date;
    } else {
        $dataset[] = 0;
    }
} 
```
I haven't tested above code
Edit: forgot that it was the number of views that should be in the dataset but this should give you the right idea how to do it anyway
Edit1,5: changed the foreach loop 
Edit2: in_array will probably not work either like this because sqlDates is more complex than a simple one dimensional array

**Comment by jackttcoms** [comment]
Ok so here is the code, does that look correct to you? 

```
        $sqlDatesas = $this->m->graphtest();
$allDates = GetCurrentWeekDates();
$dataset = [];
foreach ($sqlDatesas as $date) {
    if (in_array($date, $allDates)) {
        $dataset[] = $date;
    } else {
        $dataset[] = 0;
    }
} 

        $viewsGraph = [
            'labels' => $allDates,
            'datasets' => [[
                'data' => $dataset,
                'backgroundColor' => 'rgba(0, 123, 255, 0.21)',
                'borderColor' => '#005cbf',
                'label' => 'Views'
            ]]
        ];
        $options = [
            'bezierCurve' => false,
            'responsive' => true,
            'elements' => [
                'line' => [
                    'tension' => 0
                ]
            ],
            'scales' => [
              'yAxes' => [[
                  'ticks' => [
                      'beginAtZero' => true,
                  ]
              ]]  
            ],
        ];
        $attributes = ['id' => 'example', 'width' => 500, 'height' => 200];
        $Line = new ChartJS('line', $viewsGraph, $options, $attributes);
```

This is what it currently looks like: 
![image](https://user-images.githubusercontent.com/26184209/47572603-4b9dea80-d933-11e8-911f-effc1b529e5a.png)

Edit: The var_dump gets all the data in db:
`array(2) { [0]=> array(2) { ["DATE( date )"]=> string(10) "2018-10-21" ["COUNT(*)"]=> string(1) "2" } [1]=> array(2) { ["DATE( date )"]=> string(10) "2018-10-25" ["COUNT(*)"]=> string(1) "9" } } `

Thanks again!

**Comment by adamgeorgsson** [comment]
I did some updates on my previous post but you were too quick to see them ;)
Can you do an echo `"<pre>" . print_r($sqlDatesas, true) . "</pre>";`

**Comment by jackttcoms** [comment]
it displays this:

```
Array
(
    [0] => Array
        (
            [DATE( date )] => 2018-10-21
            [COUNT(*)] => 2
        )

    [1] => Array
        (
            [DATE( date )] => 2018-10-25
            [COUNT(*)] => 9
        )

)
```

Edit: What do you recommend i do other than in_array as my arrays are more complex than 1d ones as you said above 👍 

Thanks

**Comment by adamgeorgsson** [comment]
Firstly you need to name the columns in the sql query

```
select DATE( date ) as "date", COUNT(*) as "count"
                from chewi_views
                group by DATE( date )
```
Then I think a rebuild of that result array is necessary like this:
```
$sqlDatesas = $this->m->graphtest();
$sqlDates = [];
foreach ($sqlDatesas as $row) {
    $sqlDates[$row['date']] = $row['count'];
}
```
The foreach will be like this instead
```
$allDates = GetCurrentWeekDates();
$dataset = [];
foreach ($allDates as $date) {
    if (array_key_exists($date, $sqlDates)) {
        $dataset[] = $sqlDates[$date];
    } else {
        $dataset[] = 0;
    }
}
```

**Comment by jackttcoms** [comment]
Thankyou thankyou!!!!!!!! Thankyou very much!

One last question, for design purposes, is there a way to make the `max ` always 1 or so bigger so it's not touching the top?
![image](https://user-images.githubusercontent.com/26184209/47574285-290dd080-d937-11e8-8e3c-e7abb075de37.png)

Thanks again

**Comment by adamgeorgsson** [comment]
You're welcome :)
