### ISSUE TITLE
Can not find folder vendor and autoload.php

### ISSUE THREAD

**Issue by jajasuparja** [Ejdamm/Chart.js-PHP#6]
Hi,

I tried to download this code. But get error : Warning: require(../vendor/autoload.php): failed to open stream: No such file or directory . I can not found folder vendor and autoload.php

thanks,

jajas

**Comment by adamgeorgsson** [comment]
Hi,

autoload.php is a file that auto-generates when you install it via composer. https://getcomposer.org/
If you don't like this way you could try an older version like v1.0 where composer wasn't included in the project yet. https://github.com/Ejdamm/Chart.js-PHP/releases/tag/v1.0

**Comment by jajasuparja** [comment]
Hi, Thanks
