### ISSUE TITLE
Cannot set border width 

### ISSUE THREAD

**Issue by jajasuparja** [Ejdamm/Chart.js-PHP#7]
Hi,

I tired to set border width by set option bellow
```$datasets = array(
                    array('data' => $data, 'label' =>'Jumlah')+$colors[$color_index], 'borderwidth'=>1,
                    );
```

Then i got this link : https://jsfiddle.net/kewmh8w0/   but confuse to implement in your code framework

Thanks in advance

**Comment by adamgeorgsson** [comment]
`array('data' => $data, 'label' =>'Jumlah')+$colors[$color_index]`  appends the color array to the dataset array.
Adding `, 'borderWidth'=>1,` will not append to the dataset array, it will rather just create a new entry. 

 `array('data' => $data, 'label' =>'Jumlah')+$colors[$color_index] + array('borderWidth'=>1),`
 Above line would do what you want, but a cleaner way is to write it like this:
`array('data' => $data, 'label' => 'Jumlah', 'borderWidth' => 1) + $colors[$color_index],`


Note that the 'W' in borderWidth is capital.

**Comment by jajasuparja** [comment]
Hi,

It works! thanks
