### ISSUE TITLE
add thousand sparator to chart label

### ISSUE THREAD

**Issue by jajasuparja** [Ejdamm/Chart.js-PHP#8]
Hi,

i tried to add thousand separator to my chart but still got error. bellow is my code using callback function but it doesn't work.  need your help for this issue. 

$options = array(
        'responsive' => true,
        'callbacks'=>array(
                    'label'=>function (tooltipItems, data) (
                        return data.datasets[tooltipItems.datasetIndex].label + ' : ' + tooltipItems.yLabel.toLocaleString();
                    )
        )        
        'scales' => array(
            'yAxes' => array(
                array(
                    'scaleLabel' => array(
                        'display' => $showYaxes,
                        'labelString' =>$yaxeslabel,
                        'fontSize' =>10,
                        'fontStyle'=>'bold',
                        'borderWidth'=>1,
                    ),
                    'ticks'=>array(
                    'beginAtZero'=> true,
                  )
                   
                )
            ),
            'xAxes'=> array(
                array(
                  'gridLines'=>array(/*
                    'zeroLineColor'=> "black",
                    'zeroLineWidth'=> 2*/
                    'display'=> true
                  ),
                  'ticks'=>array(
                    'autoSkip'=>false,
                    'maxRotation'=> 30,
                    'minRotation'=> 30,                    
                  ),
                  'scaleLabel'=>array(
                  'display'=> false,
                  'fontSize'=>16,
                  'labelString'=> $chartTitle
                  )
                )  
            )
        ),
        'legend' => array (
            'display' => $displayLegend,
            'position' => $legendPos,
            'labels' => array (
            'fontSize' => 12,
            'usePointStyle'=> true,
            )
        ),
        'title'=>array (
            'display'=>true,
            'text'=> $chartTitle,
            'fontSize' => 12,
            'position'=>$titlePos

        )
    );

Thanks,
Jajas

**Comment by adamgeorgsson** [comment]
Hi! Sorry for the late response. This issue was noticed in #3 and my solution was to send in the callback function as a string. So you need to enclose it in ' or ".

**Comment by jajasuparja** [comment]
i tried your sample using this syntax 

```$options = array(
    'responsive' => false,
    'tooltips' => array(
        'callbacks' => array(
            'label' => 'function(tooltipItem, data){return "Hello world";}'
        )
    )
);


and i got error on browser console
Chart.js:8132 Uncaught TypeError: callbacks.label.call is not a function
    at Chart.js:8132
    at Object.helpers.each (Chart.js:4811)
    at ChartElement.getBody (Chart.js:8125)
    at ChartElement.update (Chart.js:8205)
    at Chart.Controller.eventHandler (Chart.js:4493)
    at Chart.Controller.<anonymous> (Chart.js:4415)
    at HTMLCanvasElement.events.(anonymous function)```

**Comment by adamgeorgsson** [comment]
Which version of Chart.js-PHP did you end up using? Passing callbacks functions is one of the new features in 2.0.

**Comment by jajasuparja** [comment]
[Chartjs.zip](https://github.com/Ejdamm/Chart.js-PHP/files/2205384/Chartjs.zip)
im using this attached version
/*!
 * Chart.js
 * http://chartjs.org/
 * Version: 2.3.0
 *
 * Copyright 2016 Nick Downie
 * Released under the MIT license
 * https://github.com/chartjs/Chart.js/blob/master/LICENSE.md
 */

and call this script to generate chart

<script src="assets/Chartjs/Chart.js"></script> <script src="assets/Chartjs/driver.js"></script>

**Comment by jajasuparja** [comment]
and call this script to generate chart
<script src="<?php echo base_url()?>assets/Chartjs/Chart.js"></script>
<script src="<?php echo base_url()?>assets/Chartjs/driver.js"></script>

**Comment by adamgeorgsson** [comment]
Yeah but that is Chart.js, I was asking about the PHP wrapper Chart.js-PHP. It's easy to mix up the names when they are so similar.

**Comment by jajasuparja** [comment]
[ChartJS.zip](https://github.com/Ejdamm/Chart.js-PHP/files/2209505/ChartJS.zip)
another file in my project i got this one.

**Comment by adamgeorgsson** [comment]
That looks like the 1.0 version. So if you want to use callbacks you have to upgrade to 2.0 and install it via composer as I told you in #6.

**Comment by jajasuparja** [comment]
for version 2.0, is there any sample package like version 1.0
I am newbe for using composer.

**Comment by adamgeorgsson** [comment]
Yes at https://github.com/Ejdamm/Chart.js-PHP/releases but you will still
need to use composer. There are easy to follow-guides at Composer's
website. It is probably possible to remove some lines of code to use it
without composer but i am not able to help with that for a couple of weeks.

Den fre 20 juli 2018 10:19jajasuparja <notifications@github.com> skrev:

**Comment by jajasuparja** [comment]
![image](https://user-images.githubusercontent.com/32153223/43031937-22d91db2-8cd6-11e8-8c65-3bd1982e4e2e.png)

Run composer got this warning. if i have to upgrade my php version. lot of thing to re-configure. meanwhile i will use native chart.js script

**Comment by adamgeorgsson** [comment]
One way to use 2.0 without composer would be to just replace the line 
`require '../vendor/autoload.php';`
with
`require '../src/ChartJS.php';`
